### ISSUE TITLE
[w13] sync.RWMutex - Solving readers-writers problems

### ISSUE THREAD

**Issue by fivezh** [gocn/translator#1]
Source: [sync.RWMutex - Solving readers-writers problems](https://medium.com/golangspec/sync-rwmutex-ca6c6c3208a0)

标题：`sync.RWMutex: 解决读者写者问题(Readers-writers problems)`

二组选定w14翻译

**Comment by polaris1119** [comment]
这篇文章，GCTT 在 2018 年 9 月份就翻译发布了，兄弟们别重复工作啊，要翻译建议先看看是否有人翻译了。https://github.com/studygolang/GCTT/pull/822

**Comment by Chyroc** [comment]
https://github.com/gocn/translator/pull/13/files 完成，关闭本 issue。
