### ISSUE TITLE
[W17] Making and Using HTTP Middleware 翻译

### ISSUE THREAD

**Issue by fivezh** [gocn/translator#28]
本文第2组翻译。
原文地址：https://www.alexedwards.net/blog/making-and-using-middleware

**Comment by polaris1119** [comment]
额~有翻译重复文章 https://studygolang.com/articles/12901 

https://github.com/studygolang/GCTT 在 2018年5月份就翻译该文了

**Comment by fivezh** [comment]
> 额~又翻译重复文章 https://studygolang.com/articles/12901
> 
> https://github.com/studygolang/GCTT 在 2018年5月份就翻译该文了

开展翻译前根据原文地址和标题搜下，降低重复工作的可能
